name: Proof exception request
description: Request an exception when Proof cannot be provided.
title: "[Proof-Exception] <short reason>"
labels: []
body:
  - type: textarea
    id: reason
    attributes:
      label: Why Proof cannot be provided
      placeholder: Constraints, time, missing environment, etc.
    validations:
      required: true
  - type: textarea
    id: mitigation
    attributes:
      label: Mitigation / alternative evidence
      placeholder: What can you provide instead? What risk mitigation?
    validations:
      required: true
